### ISSUE TITLE
High CPU load on Raspberry Pi

### ISSUE THREAD

**Issue by mpw-eng** [peterwoj/homebridge-blynk-platform#15] opened 2020-11-19 01:07 UTC
* **Solved**
Used the plugin settings web interface page, which added;
`"pollerseconds": 1,`
This fixed the high CPU load problem.

Please update the sample configuration settings on the repository home page to include this setting ;-)

* ** ********************************************************************************************** **

Hi Peter, 

Thank you for developing this plugin!

I've noticed that my Raspberry Pi CPU load goes from 1% to 40% when the plugin is configured on Homebridge.  Is this because the device polling frequency is too high?

There is another older blynk-homebridge plugin that is currently broken (I think because it's not exposing all the required characteristics for Homebridge 1.x.x).  However, this version allowed the polling frequency for each device to be specified.  Could you take a look and perhaps collaborate with the owner of this repository?

* **homebridge-blynk repository link**
[https://github.com/ilcato/homebridge-blynk](url)

Thanks!

Plugin config;

`{
    "bridge": {
        "name": "Homebridge XXXX",
        "username": "xx:xx:xx:xx:xx:xx",
        "port": 51238,
        "pin": "000-00-000"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "platform": "BlynkPlatform",
            "serverurl": "http://192.168.1.101:8080",
            "devices": [
                {
                    "manufacturer": "Me",
                    "name": "LED Dimmer",
                    "token": "*******************************",
                    "deviceId": "*********",
                    "discover": false,
                    "accessories": [
                        {
                            "model": "LED Dimmer",
                            "name": "Light",
                            "pintype": "VIRTUAL",
                            "pinnumber": 0,
                            "type": "SWITCH"
                        }
                    ]
                }
            ]
        }
    ]
}`

* **Node.js Version**:  v14.15.0 

* **NPM Version**:  v6.14.8 

* **Homebridge Version**:  v1.1.6

* **Operating System**: Raspbian
* **Process Supervisor**: hb-service 
* **homebridge-blynk-platform**: v0.2.5

**Comment by peterwoj** [comment] 2021-05-24 04:31
Should be fixed, this looks to have been caused by missing correct defaults for pollerseconds.  It would default to <oops>1ms</oops>

**Comment by peterwoj** [comment] 2021-06-06 17:31
Caused by flood on the blynk.server due to not respecting how frequently the status should be checked.

**Closed** 2021-06-06 17:30 UTC
